[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    arduino-libraries/NTPClient
    xreef/PCF8574 library@^2.4.0

build_flags =
    -D DEVICEIQ_VERSION=\"0.1.0\"
    -D CORE_DEBUG_LEVEL=0