[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson
    arduino-libraries/NTPClient
    xreef/PCF8574 library@^2.4.0

build_flags =
    -D DEVICEIQ_VERSION=\"0.1.0\"
    -D CORE_DEBUG_LEVEL=0
